/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unisul.trabalhointegrador.interfac;

import br.unisul.trabalhointegrador.controller.Principal;
import javax.swing.WindowConstants;

/**
 *
 * @author larissadiniz
 */
public class BuscarRotas extends javax.swing.JFrame {

    private Principal principal;

    /**
     * Creates new form BuscarRotas
     */
    public BuscarRotas(Principal principal) {
        initComponents();
        this.principal = principal;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblNomeMotorista = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtNomeMotorista = new javax.swing.JTextField();
        tipoBusca = new javax.swing.JComboBox<>();
        btnBuscarRotas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tipo de Busca");

        lblData.setText("Data");

        lblNomeMotorista.setText("Nome do Motorista");
        lblNomeMotorista.setEnabled(false);

        txtNomeMotorista.setEnabled(false);

        tipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Data", "Nome Motorista" }));
        tipoBusca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoBuscaItemStateChanged(evt);
            }
        });

        btnBuscarRotas.setText("Buscar");
        btnBuscarRotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(jLabel1)
                            .addComponent(lblNomeMotorista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoBusca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtData)
                            .addComponent(txtNomeMotorista)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnBuscarRotas)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeMotorista)
                    .addComponent(txtNomeMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarRotas)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoBuscaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoBuscaItemStateChanged
        switch (tipoBusca.getSelectedIndex()) {
            case 0:
                lblData.setEnabled(true);
                txtData.setEnabled(true);
                lblNomeMotorista.setEnabled(false);
                txtNomeMotorista.setEnabled(false);
                break;
            case 1:
                lblData.setEnabled(false);
                txtData.setEnabled(false);
                lblNomeMotorista.setEnabled(true);
                txtNomeMotorista.setEnabled(true);
                break;
        }
    }//GEN-LAST:event_tipoBuscaItemStateChanged

    private void btnBuscarRotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRotasActionPerformed
        if (tipoBusca.getSelectedIndex() == 0) {
            principal.buscarRotas(tipoBusca.getSelectedIndex(), txtData.getText());
        } else {
            principal.buscarRotas(tipoBusca.getSelectedIndex(), txtNomeMotorista.getText());
        }
    }//GEN-LAST:event_btnBuscarRotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRotas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblNomeMotorista;
    private javax.swing.JComboBox<String> tipoBusca;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNomeMotorista;
    // End of variables declaration//GEN-END:variables
}
